### ISSUE TITLE
Network Details

### ISSUE THREAD

**Issue by FeboReigns** [ZhengPeng7/GLCNet#3]
Thank you for your excellent work！I have two questions about network details.
1.Scene Context:
对于一张图片的每一个人来说，Scene Context 是怎么区别呢。是不是每个人所对应Scene Context都是相同的？都是该图片resnet最后输出的特征，经过CE模块后变为一个2048维的向量。应该是这样，但是我还想找你确认一下。
For everyone in a picture, how does Scene Context make the difference? Is the Scene Context the same for everyone? These are the features of the last output of the image resnet. After passing through the CE module, it becomes a vector of 2048 dimensions.It should be so, but I still want to check with you.

2.Group Context
在 Group CE之前，128维的特征向量是怎么来的？
您是把所有正样本的特征变成一个128维的特征吗？假如图中有两个人，那么有两个ROI区域。每一个ROI就有一个256维的特征向量，您把两个256的特征向量变维一个128维的向量。如果是三个人的话，就把三个256维的向量变为一个128维的向量。还有具体您是怎么实现的，直接cat变为256xN维的特征，然后再做一个1X1的卷积，变为128通道的特征，是这样吗？
Before Group CE, how did the 128-dimensional eigenvectors come from?
Are you turning all the features of a positive sample into a 128-dimensional feature? If there are two people in the graph, then there are two ROI regions. Each ROI has a 256-dimensional eigenvector, and you turn two 256 eigenvectors into a 128-dimensional vector. If it were three people, three vectors of 256 dimensions would be changed into one vector of 128 dimensions. And how exactly did you achieve this, directly cat into a 256*N-dimensional feature, and then do a 1X1 convolution to become a 128-channel feature, is that right?

**Comment by ZhengPeng7** [comment]
Sorry for my delayed response, and thanks for your interest and questions about our work!

1. Scene Context:
    对于同一张图片的不同人来说, scene context是相同的. 这个context被填到这个人的原re-id后, 用于更新他的identity特征.
    For different persons in a single image, the scene context features assigned to them are exactly the same. This context feature is then appended to the original re-id feature, which is then used to update his or her identity feature.

2. Group Context:
    128维的group context特征向量是由RoI-Align后得到的正样本们融合得到的特征. 假如图中有N人, 就把这N个框内特征给收集, 然后平均为一个特征. 但是特征长度的话, 由于是经过[主图](https://github.com/ZhengPeng7/GLCNet/raw/main/README.assets/GLCNet_arch_v2.svg)中的`Res5`, 这里的特征就已经是2048d的特征了, 因此就是直接进过CE模块, 得到了128d的group特征. 当然, 关于特征长度你可以直接在`config.py`进行修改, 来测试不同context和原reid特征不同权重占比下的效果.
    The 128d group context feature vectors are obtained from the fusion of the positive samples after the RoI-Align. So, suppose there are N persons in the image, and features of information inside these N boxes are collected and averaged into a single feature. However, when it comes to the length of features, these features are already 2048d features because of that they are produced by the `Res5` as shown in the [main figure](https://github.com/ZhengPeng7/GLCNet/raw/main/README.assets/GLCNet_arch_v2.svg). Thus, they are simply fed into CE block and get the 128d group feature. What's more, you can adjust the length of different features in `config.py` directly to test the effect of assigning these context features different weights.

Have a nice day!

**Comment by ZhengPeng7** [comment]
If you have any other question or want to continue it, feel free to re-open this issue:)
