### ISSUE TITLE
http://movienet.site unable to access, are there any other access methods 

### ISSUE THREAD

**Issue by houcuicui** [ZhengPeng7/GLCNet#4]
http://movienet.site unable to access, are there any other access methods

**Comment by ZhengPeng7** [comment]
Yeah, but it seems that the authors leave it alone ([issue in MovieNet](https://github.com/movienet/movienet-tools/issues/37))...

But you can still download the necessary part used in GLCNet from my [google-drive](https://drive.google.com/drive/folders/1kUr7v9_LUSSjW5PyNbGqaiM6peXNvbiU). If you only want to use MovieNet-PS, you can download the `frame-CS.zip` or its fractions. The `frames.zip` is all the original frames in MovieNet, which I downloaded before.

**Comment by houcuicui** [comment]
> Yeah, but it seems that the authors leave it alone ([issue in MovieNet](https://github.com/movienet/movienet-tools/issues/37))...
> 
> But you can still download the necessary part used in GLCNet from my [google-drive](https://drive.google.com/drive/folders/1kUr7v9_LUSSjW5PyNbGqaiM6peXNvbiU). If you only want to use MovieNet-PS, you can download the `frame-CS.zip` or its fractions. The `frames.zip` is all the original frames in MovieNet, which I downloaded before.

thank you!

**Comment by houcuicui** [comment]
> Yeah, but it seems that the authors leave it alone ([issue in MovieNet](https://github.com/movienet/movienet-tools/issues/37))...
> 
> But you can still download the necessary part used in GLCNet from my [google-drive](https://drive.google.com/drive/folders/1kUr7v9_LUSSjW5PyNbGqaiM6peXNvbiU). If you only want to use MovieNet-PS, you can download the `frame-CS.zip` or its fractions. The `frames.zip` is all the original frames in MovieNet, which I downloaded before.

您好，能问一下有没有百度网盘，谷歌云盘翻墙下载实在太慢了

**Comment by ZhengPeng7** [comment]
百度网盘之前好像没传过，我可以晚上回去传一下, 好了贴上来。

**Comment by houcuicui** [comment]
> 百度网盘之前好像没传过，我可以晚上回去传一下, 好了贴上来。

非常感谢您，麻烦了

**Comment by ZhengPeng7** [comment]
Hi, I've updated the Baidu Disk links in [README](https://github.com/ZhengPeng7/GLCNet/blob/main/README.md#movienet-cs). Good luck.
