### ISSUE TITLE
RuntimeError: Boolean value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by ChenHuyoo** [ZhengPeng7/GLCNet#5]
您好！
当我将self.psn_feat_labelledOnly 设置为True时，出现了RuntimeError: Boolean value of Tensor with more than one value is ambiguous 这个错误，使用的数据集为cuhk，这是怎么回事呢？

**Comment by ZhengPeng7** [comment]
Hi, thanks for your interest in our project.
最近实在太累了, 身体有点吃不消. 我过一两天会尽快把代码重跑下, 看看问题怎么回事并把解决.
请耐心稍后哈 :)

**Comment by ZhengPeng7** [comment]
哈喽, 实在不好意思, 都差点忘了这事了. 因为这个选项后来没有开启, 有的bug就没都暴露出来. 其实就是我犯了个比较低级的numpy/PyTorch用法错误...
把`seqnet.py`里的`0 < box_pid_label < 1`改为`(0 < box_pid_label) * (box_pid_label < 1)`就正确啦.
