### ISSUE TITLE
About GLC method

### ISSUE THREAD

**Issue by YangJae96** [ZhengPeng7/GLCNet#7]
Hello. Thank you for great work.

I was wondering if adding your GCL module improves the performance in PRW and CUHK-SYSU datasets also.

Does the performance only improve in MovieNet test dataset?

**Comment by ZhengPeng7** [comment]
Thanks for your interest :)
But we don't have the GCL module, only the global-local context here.
Currently, the main improvement is from the global scene context.
And our GLCNet can greatly improve the original network on the MovieNet-PS test set and CUHK-SYSU.
It can also improve the top-1 on PRW a lot, but only very little on the mAP of PRW.
