### ISSUE TITLE
Problems with run demo.py

### ISSUE THREAD

**Issue by BeiningWu** [ZhengPeng7/GLCNet#8]
When I run demo.py using comman as follow:
```
python3 demo.py --cfg configs/prw.yaml --ckpt ckpts/prw_469.pth 
```
A size mismatch error occurs as follow:
Traceback (most recent call last):
  File "demo.py", line 87, in <module>
    main(args)
  File "demo.py", line 58, in main
    resume_from_ckpt(args.ckpt, model)
  File "/home/wbn/GLCNet/utils/utils.py", line 417, in resume_from_ckpt
    model.load_state_dict(my_state_dict, strict=False)
  File "/home/wbn/.conda/envs/glcnet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SeqNet:
        size mismatch for roi_heads.embedding_head.projectors.feat_res4.0.weight: copying a param with shape torch.Size([256, 1024]) from checkpoint, the shape in current model is torch.Size([128, 2048]).
        size mismatch for roi_heads.embedding_head.projectors.feat_res4.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for roi_heads.embedding_head.projectors.feat_res4.1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for roi_heads.embedding_head.projectors.feat_res4.1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for roi_heads.embedding_head.projectors.feat_res4.1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for roi_heads.embedding_head.projectors.feat_res4.1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).

I’m sure my pytorch version is correct, I don't konw why it happend.
Could you help me ? Thanks.

**Comment by ZhengPeng7** [comment]
Hi, well, I think the problem here is caused by the different value of the length of `feat_res4` in the setting or the further concatenation you used on it. You should keep them consistent.

**Comment by fernandorovai** [comment]
I have the same issue using the code straight from the repo.
Where should I change the feat_res4 setting? It's not matching the weights.
Could you share your exp config files, please?
